### ISSUE TITLE
New Paper

### ISSUE THREAD

**Issue by vlongle** [dougefla/Awesome-Articulated-Object-Understanding#3]
Hello,

Thank you for this awesome repo! We recently released a paper -- Articulate Anything -- which does reconstruction from texts, images or videos. Would you consider adding this paper?

Project page: https://articulate-anything.github.io/
Code: https://github.com/vlongle/articulate-anything
Paper: https://arxiv.org/abs/2410.13882

Thanks!

**Comment by dougefla** [comment]
Sure, added. Thank you for contributing.
